config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  devise_for :models
  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :shops
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :shop

end

app/models/shop.rb
class Shop < ApplicationRecord
	has_and_belongs_to_many :models
	has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if current_model
      stores = current_model.shops
      @categories = category
      sort_by_category = params[:category] || @categories
      type = params[:type] || "price"
      if stores.empty?
        @products = []
      else
        @products = stores.select('shops.*,products.*').joins(:products)
                                               .where(products: {breadcrumb: sort_by_category})
                                               .merge(Product.order("#{type}": :desc))
                                               .page(params[:page]).per(10)
      end
      @category_name = category_name
    end
  end

  private

  def category()
  	cat = Product.select("distinct(products.breadcrumb)")
    cat.map {|val| val[:breadcrumb]}
  end

  def category_name()
    params[:category] ? params[:category] : "All"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClientUi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<nav class="navbar navbar-default">
	  <div class="container">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="/">Beta version</a>
	    </div>
	    <ul class="nav navbar-nav navbar-right">
	    	<% unless model_signed_in? %>
	    	<li>
	    			<%= link_to "Sign up", new_model_registration_path %>
	    	</li>
	    	<li>
	    			<%= link_to "Sign in", model_session_path %>
	    	</li>
	    	<% else %>
		    	<li>
		    			<%= link_to "Sign out(#{current_model.email})", destroy_model_session_path, method: :delete%>
		    	</li>
		    <% end %>
	    </ul>
	  </div>
	</nav>

	<div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/delit.html.erb
<% @cat.each do |ds| %>
<%= link_to "#{ds}", welcome_delit_path(:category => ds), class: 'btn btn-default' %>
<% end %>
<br>
<br>
<%= form_tag(welcome_delit_path, method: "get") do %>
  <%= label_tag(:q, "Choose category:") %>
  <br>
  <%= select_tag("category", options_for_select(@cat)) %>
  <br>
  <br>
  <%= submit_tag("Confirm") %>
<% end %>
<br>
<br>

<div class="table-responsive">
	<table class="table table-bordered">
		<thead> 
			<tr>
			 <th>Shop name <%= link_to "&dArr;".html_safe, welcome_delit_path(:type => "shop_id", :category => params[:category]), class: 'btn btn-default' %></th>
			 <th>Image</th> 
			 <th>Name <%= link_to "&dArr;".html_safe, welcome_delit_path(:type => "name", :category => params[:category]), class: 'btn btn-default' %></th> 
			 <th>Price <%= link_to "&dArr;".html_safe, welcome_delit_path(:type => "price", :category => params[:category]), class: 'btn btn-default' %></th> 
			 <th>Weight <%= link_to "&dArr;".html_safe, welcome_delit_path(:type => "weigth", :category => params[:category]), class: 'btn btn-default' %></th> 
			</tr> 
		</thead>
		<tbody>
<% @products.each do |i| %>
<tr>
<th scope="row"><span><%= Shop.find(i.shop_id).shop_name %></span></th>
<% i.image_url = "http://sushihouse.by" + i.image_url if i.image_url[/\/upload\//]%>
<td><img src="<%= i.image_url %>" style="width:220px;height:100px"></td>
<td><span><%= i.name %></span></td>
<td><span><%= i.price %></span></td>
<td><span><%= i.weigth.to_s + " г" %></span></td>
</tr> 
<% end %>
</tbody>
	</table>
<%= paginate @products %>

app/views/welcome/index.html.erb
<% if model_signed_in? %>
<%= form_tag(welcome_index_path, method: "get") do %>
  <%= label_tag(:q, "Choose category:") %>
  <br>
  <%= select_tag("category", options_for_select(@categories)) %>
  <br>
  <br>
  <%= submit_tag("Confirm") %>
<% end %>
<br>
<br>
<h1><%= @category_name %></h1>
<div class="table-responsive">
	<table class="table table-bordered">
		<thead>
			<tr>
			 <th>Shop name <%= link_to "&dArr;".html_safe, welcome_index_path(:type => "shop_id", :category => params[:category]), class: 'btn btn-default' %></th>
			 <th>Image</th>
			 <th>Name <%= link_to "&dArr;".html_safe, welcome_index_path(params.permit(:category).merge(type: "name")), class: 'btn btn-default' %></th>
			 <th>Price <%= link_to "&dArr;".html_safe, welcome_index_path(:type => "price", :category => params[:category]), class: 'btn btn-default' %></th>
			 <th>Weight <%= link_to "&dArr;".html_safe, welcome_index_path(:type => "weigth", :category => params[:category]), class: 'btn btn-default' %></th>
			</tr>
		</thead>
		<tbody>
<% @products.each do |i| %>
<tr>
<th scope="row"><span><%= Shop.find(i.shop_id).shop_name %></span></th>
<% i.image_url = "http://sushihouse.by" + i.image_url if i.image_url[/\/upload\//]%>
<td><img src="<%= i.image_url %>" style="width:220px;height:100px"></td>
<td><span><%= i.name %></span></td>
<td><span><%= i.price %></span></td>
<td><span><%= i.weigth.to_s + " г" %></span></td>
</tr>
<% end %>
</tbody>
	</table>
<%= paginate @products unless @products.empty? %>
  </div>
<%	 end %>